name: Publish Package to npmjs
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout to main branch
        uses: actions/checkout@v4
      - name: install and build
        run: npm ci
      - name: publish to npm registry
        uses: action/setup-node@v3
        with:
          node-version: '21.x'
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@hivary'
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
