name: Publish to NPM

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
          node-version: '21.x'
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@hivary'
    - name: Install Deps
      run: npm install
    - name: Build Package
      run: npm run prepare
    - name: Pack build
      run: npm pack
    - name: Publish to NPM
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}